#
# Build:
#    docker build -t redeagleeye/catalyst-prod:0.5.21.CUSTOM11 -f Dockerfile-prod .
#
# Run:
#    docker run -v /some/folder:/app -v ~/.catalyst:/root/.catalyst --name catalyst-prod -it enigmampc/catalyst-prod
#
# Exec:
#    docker exec -it catalyst-prod catalyst run -f /projects/my_algo.py --start 2015-1-1 --end 2016-1-1 /projects/result.pickle
#
FROM python:3.6

#
# set up environment
#
ENV TINI_VERSION v0.10.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

#
# install TA-Lib and other prerequisites
#

RUN apt-get -y update \
    && apt-get -y install libfreetype6-dev libpng-dev libopenblas-dev liblapack-dev gfortran \
    && curl -L https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz | tar xvz

#
# build and install catalyst from source.  install TA-Lib after to ensure
# numpy is available.
#

WORKDIR /ta-lib

RUN pip install 'numpy==1.14.0' \
  && pip install 'scipy==1.0.0' \
  && pip install 'pandas==0.19.2' \
  && ./configure --prefix=/usr \
  && make \
  && make install \
  && pip install TA-Lib \
  && pip install matplotlib

#
# build and install the catalyst package into the image
#

ADD etc /catalyst/etc
ADD versioneer.py setup.* /catalyst/
ADD catalyst/lib /catalyst/catalyst/lib
ADD catalyst/assets /catalyst/catalyst/assets
ADD catalyst/data /catalyst/catalyst/data
ADD catalyst/_protocol.pyx /catalyst/catalyst/_protocol.pyx
ADD catalyst/gens/sim_engine.pyx /catalyst/catalyst/gens/sim_engine.pyx
ADD catalyst/utils/calendars/_calendar_helpers.pyx /catalyst/catalyst/utils/calendars/_calendar_helpers.pyx
WORKDIR /catalyst
RUN pip install -e .

ADD .git /catalyst/.git
ADD .gitattributes /catalyst/.gitattributes
ADD catalyst /catalyst/catalyst
WORKDIR /app

CMD ["/bin/bash"]